// Auto-generated by n8n. Do not edit manually.
export const tenders = [
  {
    "id": "4555933",
    "title": "Rusagro集团农业业务方向提议采购存放于Agrotechnologii（坦波夫州）、Rusagro-Invest（别尔哥罗德州）、Kshenagro（库尔斯克…）等公司粮仓和场地的谷物",
    "originalTitle": "Сельскохозяйственное бизнес-направление ГК «Русагро» предлагает рассмотреть приобретение зерна, хранящегося на элеваторах и площадках ООО «Агротехнологии» (Тамбовская обл.), ООО «Русагро-Инвест» (Белгородская обл.), ООО «Кшеньагро» (Курская...",
    "category": "未分类",
    "procurementType": "询价",
    "organizer": "ООО \"Русагро-Центр\"",
    "publishTime": "2026-08-11T17:46:00+03:00",
    "deadline": "2026-08-13T12:00:00+03:00",
    "region": "308002 俄罗斯",
    "summary": "俄罗斯Rusagro集团农业业务板块发布粮食采购意向，拟采购储存于多家子公司粮仓和场地的谷物（涉及坦波夫州、别尔哥罗德州、库尔斯克州等）。采购方为Rusagro-Center有限责任公司。付款条件优先100%预付款，未公布价格。投标在B2B-Center电子平台以电子文档形式进行，截止时间2026-08-13 12:00。",
    "sourceUrl": "https://www.b2b-center.ru/market/selskokhoziaistvennoe-biznes-napravlenie-gk-rusagro-predlagaet/tender-4555933/#btid=2&sqh=4822be52f73038d9807b4c4775d1c0dd0300c23d&tsid=4555933003"
  },
  {
    "id": "4558794",
    "title": "采购水环真空泵ВВН2-50（考虑类似型号），用于АО \"ОЭМК им. А.А.Угарова\"，2026年",
    "originalTitle": "Закупка водокольцевого вакуумного насоса ВВН2-50 (рассмотрим аналоги) для АО \"ОЭМК им. А.А.Угарова\" в 2026г.",
    "category": "未分类",
    "procurementType": "询价",
    "organizer": "ООО УК \"МЕТАЛЛОИНВЕСТ\"",
    "publishTime": "2026-08-11T17:46:00+03:00",
    "deadline": "2026-08-14T14:00:00+03:00",
    "region": "别尔哥罗德州 斯塔里奥斯科尔",
    "summary": "采购水环真空泵ВВН2-50（接受类似型号），用于АО \"ОЭМК им. А.А.Угарова\" 的2026年需求。采购方为ООО УК \"МЕТАЛЛОИНВЕСТ\"。投标截止时间为14.08.2026 14:00。未标明总价，货币为卢布。交货条件DDP斯塔里奥斯科尔，付款建议延期至少90天。程序以电子形式在B2B-Center平台进行。",
    "sourceUrl": "https://www.b2b-center.ru/market/zakupka-vodokoltsevogo-vakuumnogo-nasosa-vvn2-50-rassmotrim-analogi/tender-4558794/#btid=2&sqh=4822be52f73038d9807b4c4775d1c0dd0300c23d&tsid=4558794004"
  },
  {
    "id": "4558552",
    "title": "在b2b/g营销任务框架内组织和开展系列营销活动的服务信息研究请求（ПКО）",
    "originalTitle": "Запрос на изучение информации (ПКО) по оказанию услуг по организации и проведению комплекса маркетинговых мероприятий в рамках задач по b2b/g маркетингу",
    "category": "广告服务",
    "procurementType": "信息研究请求（RFI）",
    "organizer": "АО \"НСПК\"",
    "publishTime": "2026-08-11T17:41:00+03:00",
    "deadline": "2026-08-20T15:00:00+03:00",
    "region": "俄罗斯",
    "summary": "俄罗斯国家支付卡公司（АО НСПК）以信息研究请求（RFI/ПКО）方式，采购在b2b/b2g营销任务框架内组织并开展一系列营销活动的服务。程序在B2B-Center电子交易平台（www.b2b-center.ru）以电子形式进行，参与者需以电子文档形式提交建议书。",
    "sourceUrl": "https://www.b2b-center.ru/market/zapros-na-izuchenie-informatsii-pko-po-okazaniiu-uslug-po-organizatsii/tender-4558552/#btid=2&sqh=4822be52f73038d9807b4c4775d1c0dd0300c23d&tsid=4558552040"
  },
  {
    "id": "4558790",
    "title": "惠普（HP）17英寸显示器",
    "originalTitle": "МОНИТОР НР, диагональ 17 дюймов",
    "category": "未分类",
    "procurementType": "询价",
    "organizer": "ПАО \"Мечел\"",
    "publishTime": "2026-08-11T17:40:00+03:00",
    "deadline": "2026-08-26T12:00:00+03:00",
    "region": "186757 俄罗斯卡累利阿共和国",
    "summary": "俄罗斯梅切尔（Мечел）公开采购17英寸惠普显示器，采用电子平台招标，未公布预算，付款条件为100%预付款，交货地点为卡累利阿共和国。",
    "sourceUrl": "https://www.b2b-center.ru/market/monitor-nr-diagonal-17-diuimov/tender-4558790/#btid=2&sqh=4822be52f73038d9807b4c4775d1c0dd0300c23d&tsid=4558790003"
  },
  {
    "id": "4558789",
    "title": "技术商务建议书征询：Escaid 110稀释剂（ООО \"Удоканская медь\"）",
    "originalTitle": "Запрос технико-коммерческого предложения на Разбавитель Escaid 110 для ООО \"Удоканская медь\"",
    "category": "化学/化工",
    "procurementType": "询价（RFP）",
    "organizer": "ООО \"Удоканская медь\"",
    "publishTime": "2026-08-11T17:37:00+03:00",
    "deadline": "2026-08-27T12:00:00+03:00",
    "region": "674159 俄罗斯外贝加尔边疆区卡拉尔区乌多坎镇法布里奇纳亚街1号",
    "summary": "俄罗斯乌多坎铜业（ООО \"Удоканская медь\"）正征集Escaid 110稀释剂的技术商务建议书，采购量178吨。报价未公开，付款条件为签署ТОРГ-12/УПД后60天付清。投标截止2026年8月27日12:00，交货地点为外贝加尔边疆区新查拉站/乌多坎镇。有意向的供应商可登录B2B-Center平台参与。",
    "sourceUrl": "https://www.b2b-center.ru/market/zapros-tekhniko-kommercheskogo-predlozheniia-na-razbavitel-escaid-110/tender-4558789/#btid=2&sqh=4822be52f73038d9807b4c4775d1c0dd0300c23d&tsid=4558789004"
  },
  {
    "id": "4558792",
    "title": "出售位于俄罗斯克拉斯诺达尔边疆区格连吉克市卡巴尔丁卡村普罗列塔尔斯卡亚街45号的不动产",
    "originalTitle": "Продажа объекта недвижимости, расположенного по адресу: Россия, Краснодарский край, муниципальное образование город-курорт Геленджик, село Кабардинка, Пролетарская улица, дом 45",
    "category": "未分类",
    "procurementType": "询价",
    "organizer": "КБ \"Кубань Кредит\" ООО",
    "publishTime": "2026-08-11T17:36:00+03:00",
    "deadline": "2027-02-10T14:00:00+03:00",
    "region": "353480 俄罗斯",
    "summary": "出售位于俄罗斯克拉斯诺达尔边疆区格连吉克市卡巴尔丁卡村的一处不动产，价格30,000,000.00卢布（含增值税），投标截止2027年2月10日。",
    "sourceUrl": "https://www.b2b-center.ru/market/prodazha-ob-ekta-nedvizhimosti-raspolozhennogo-po-adresu-rossiia/tender-4558792/#btid=2&sqh=4822be52f73038d9807b4c4775d1c0dd0300c23d&tsid=4558792003"
  },
  {
    "id": "4558782",
    "title": "润滑油标段 №2",
    "originalTitle": "ЛОТ МАСЛА №2",
    "category": "润滑油",
    "procurementType": "询价",
    "organizer": "ООО «СИБУР»",
    "publishTime": "2026-08-11T17:32:00+03:00",
    "deadline": "2026-08-26T12:00:00+03:00",
    "region": "俄罗斯鞑靼斯坦共和国喀山市别洛莫尔斯卡亚街101号",
    "summary": "俄罗斯西布尔（SIBUR）发布润滑油标段№2采购，采用电子形式在B2B-Center平台进行。未标注总价，付款条件为100%预付款。投标截止时间：2026年8月26日12:00，交货地址：俄罗斯鞑靼斯坦共和国喀山市别洛莫尔斯卡亚街101号。",
    "sourceUrl": "https://www.b2b-center.ru/market/lot-masla-2/tender-4558782/#btid=2&sqh=4822be52f73038d9807b4c4775d1c0dd0300c23d&tsid=4558782003"
  },
  {
    "id": "4558768",
    "title": "燃料润滑油（ГСМ）供应，列索西比尔斯克（交货地址可调整至克拉斯诺亚尔斯克）；优先原装；报价须注明包装类型和容量为包装的倍数；包装要求：桶/罐置于托盘并用打包带捆扎，按ГОСТ 15846-2002...",
    "originalTitle": "ГСМ г. Лесосибирск (возможна корректировка адреса в г. Красноярск) Приоритет - оригинал В КП обязатльно указывать вид тары и объем кратно таре. Требуемый вид упаковки - бочки/ведра на паллете стянутые стреп лентами, согласно ГОСТу 15846-2002...",
    "category": "燃料、润滑油（ГСМ）",
    "procurementType": "询价（征求建议书）",
    "organizer": "ООО \"ТД ПОЛИМЕТАЛЛ\"",
    "publishTime": "2026-08-11T17:30:00+03:00",
    "deadline": "2026-08-14T12:00:00+03:00",
    "region": "俄罗斯克拉斯诺亚尔斯克边疆区 列索西比尔斯克市",
    "summary": "俄罗斯买家ООО «ТД ПОЛИМЕТАЛЛ»（TD Polimetall）采购燃料润滑油（ГСМ），交货至列索西比尔斯克，预算未公布。要求原装正品，报价需注明包装类型和容量倍数，桶/罐装于托盘并按ГОСТ 15846-2002打包捆扎。付款为收到货物后30天支付100%。投标截止：2026-08-14 12:00。",
    "sourceUrl": "https://www.b2b-center.ru/market/gsm-g-lesosibirsk-vozmozhna-korrektirovka-adresa-v-g/tender-4558768/#btid=2&sqh=4822be52f73038d9807b4c4775d1c0dd0300c23d&tsid=4558768004"
  },
  {
    "id": "4558774",
    "title": "油品标段 №1",
    "originalTitle": "ЛОТ МАСЛА №1",
    "category": "未分类",
    "procurementType": "询价",
    "organizer": "ООО \"СИБУР\"",
    "publishTime": "2026-08-11T17:27:00+03:00",
    "deadline": "2026-08-26T12:00:00+03:00",
    "region": "鞑靼斯坦共和国 喀山市",
    "summary": "西布尔公司（ООО \"СИБУР\"）发布油品标段 №1 采购，编号 4558774。未公布预算和数量，付款条件为100%预付款。电子报价通过 B2B-Center 平台提交。交货地点：鞑靼斯坦共和国喀山市白海街101号。",
    "sourceUrl": "https://www.b2b-center.ru/market/lot-masla-1/tender-4558774/#btid=2&sqh=4822be52f73038d9807b4c4775d1c0dd0300c23d&tsid=4558774003"
  },
  {
    "id": "4558772",
    "title": "Caterpillar 384-9907 轴，堪察加边疆区",
    "originalTitle": "Вал 384-9907 Caterpillar, Камчатский край",
    "category": "未分类",
    "procurementType": "询价",
    "organizer": "МКАО «АРЕАЛ»",
    "publishTime": "2026-08-11T17:26:00+03:00",
    "deadline": "2026-08-18T12:00:00+03:00",
    "region": "688800 俄罗斯堪察加边疆区",
    "summary": "俄罗斯堪察加边疆区采购Caterpillar 384-9907轴（Вал），招标编号4558772。组织方为МКАО «АРЕАЛ»，报价截止2026-08-18 12:00。价格未标明，货币为卢布，付款条件为100%预付款。投标通过B2B-Center电子平台进行。",
    "sourceUrl": "https://www.b2b-center.ru/market/val-384-9907-caterpillar-kamchatskii-krai/tender-4558772/#btid=2&sqh=4822be52f73038d9807b4c4775d1c0dd0300c23d&tsid=4558772003"
  }
];

export const categories = Array.from(new Set(tenders.map((tender) => tender.category))).sort(
  (a, b) => a.localeCompare(b, "zh-CN")
);

export function getTenderById(id) {
  return tenders.find((tender) => tender.id === id);
}
