// Auto-generated by n8n. Do not edit manually.
export const tenders = [
  {
    "id": "4520153",
    "title": "销售二手UBT-203（可用状态），下瓦尔托夫斯克，Integra-Burenie LLC",
    "originalTitle": "Реализация не востребованной б/у УБТ-203 (состояние пригодное для использования по назначению), г. Нижневартовск, ООО «Интегра-Бурение»",
    "category": "未分类",
    "procurementType": "询价",
    "organizer": "ООО \"Интегра Менеджмент\"",
    "publishTime": "2026-07-09T18:20:00+03:00",
    "deadline": "2026-07-31T12:00:00+03:00",
    "region": "秋明州 下瓦尔托夫斯克",
    "summary": "组织者ООО \"Интегра Менеджмент\"出售未使用的二手УБТ-203（钻铤），状态可用。交货地点为秋明州下瓦尔托夫斯克。报价通过电子平台B2B-Center提交，100%预付款。",
    "sourceUrl": "https://www.b2b-center.ru/market/realizatsiia-ne-vostrebovannoi-b-u-ubt-203-sostoianie-prigodnoe-dlia/tender-4520153/#btid=2&sqh=91d6c9736e9aae47d654849484c5ca532b5c5a40&tsid=4520153003"
  },
  {
    "id": "4520151",
    "title": "2236 ОНК和ПЭ（根据申请МГ-019723, МГ-019274）",
    "originalTitle": "2236 ОНК и ПЭ по заявкам МГ-019723, МГ-019274",
    "category": "聚合物管",
    "procurementType": "竞价采购",
    "organizer": "АО \"ИК \"АРЛАН\"",
    "publishTime": "2026-07-09T18:16:00+03:00",
    "deadline": "2026-07-15T12:00:00+03:00",
    "region": "685000 俄罗斯",
    "summary": "俄罗斯马加丹州企业竞价采购聚合物管（ОНК和ПЭ），DDP交货至马加丹海港，付款条件为交货后60天，报价截止2026年7月15日12:00。",
    "sourceUrl": "https://www.b2b-center.ru/market/2236-onk-i-pe-po-zaiavkam-mg-019723-mg-019274/tender-4520151/#btid=2&sqh=91d6c9736e9aae47d654849484c5ca532b5c5a40&tsid=4520151004"
  },
  {
    "id": "4520147",
    "title": "出售未售出的二手钻铤УБТ-178（状态适合预期用途），下瓦尔托夫斯克市，Integra-Burenie有限责任公司",
    "originalTitle": "Реализация не востребованной б/у бурильной трубы УБТ-178 (состояние пригодное для использования по назначению), г. Нижневартовск, ООО «Интегра-Бурение»",
    "category": "未分类",
    "procurementType": "销售",
    "organizer": "ООО \"Интегра Менеджмент\"",
    "publishTime": "2026-07-09T18:16:00+03:00",
    "deadline": "2026-07-31T12:00:00+03:00",
    "region": "秋明州 下瓦尔托夫斯克市",
    "summary": "出售二手钻铤УБТ-178（状态良好，适合使用），数量未知。地点：下瓦尔托夫斯克。组织方：Интегра Менеджмент。付款条件：100%预付款。投标截止日期：2026年7月31日12:00。电子平台：B2B-Center。",
    "sourceUrl": "https://www.b2b-center.ru/market/realizatsiia-ne-vostrebovannoi-b-u-burilnoi-truby-ubt-178-sostoianie/tender-4520147/#btid=2&sqh=91d6c9736e9aae47d654849484c5ca532b5c5a40&tsid=4520147003"
  },
  {
    "id": "4520144",
    "title": "未使用过的二手钻铤УБТ-127（状态适合按用途使用）销售，下瓦尔托夫斯克市，Интегра-Бурение有限责任公司",
    "originalTitle": "Реализация не востребованной б/у бурильной трубы УБТ-127 (состояние пригодное для использования по назначению), г. Нижневартовск, ООО «Интегра-Бурение»",
    "category": "未分类",
    "procurementType": "销售/变现",
    "organizer": "ООО \"Интегра Менеджмент\"",
    "publishTime": "2026-07-09T18:09:00+03:00",
    "deadline": "2026-07-31T12:00:00+03:00",
    "region": "秋明州 下瓦尔托夫斯克",
    "summary": "销售未使用过的二手УБТ-127钻铤，状态适用，位于秋明州下瓦尔托夫斯克。采购方为Интегра-Бурение，组织方为Интегра Менеджмент。价格4,535,608.00 RUB（不含增值税），付款条件为100%预付款。投标截止2026年7月31日12:00。",
    "sourceUrl": "https://www.b2b-center.ru/market/realizatsiia-ne-vostrebovannoi-b-u-burilnoi-truby-ubt-127-sostoianie/tender-4520144/#btid=2&sqh=91d6c9736e9aae47d654849484c5ca532b5c5a40&tsid=4520144003"
  },
  {
    "id": "4520138",
    "title": "销售未使用的二手钻杆УБТ-121（状况适用于按用途使用），下瓦尔托夫斯克市，Интегра-Бурение有限责任公司",
    "originalTitle": "Реализация не востребованной б/у бурильной трубы УБТ-121(состояние пригодное для использования по назначению), г. Нижневартовск, ООО «Интегра-Бурение»",
    "category": "未分类",
    "procurementType": "询价",
    "organizer": "ООО \"Интегра Менеджмент\"",
    "publishTime": "2026-07-09T18:05:00+03:00",
    "deadline": "2026-07-31T12:00:00+03:00",
    "region": "秋明州 下瓦尔托夫斯克",
    "summary": "俄罗斯Интегра-Бурение通过其管理公司出售一根二手钻杆УБТ-121（状态良好可用），价格958850卢布（不含增值税），付款条件为100%预付款。交货地点在下瓦尔托夫斯克。投标在B2B-Center电子平台进行，截止日期2026年7月31日12:00。",
    "sourceUrl": "https://www.b2b-center.ru/market/realizatsiia-ne-vostrebovannoi-b-u-burilnoi-truby-ubt-121-sostoianie/tender-4520138/#btid=2&sqh=91d6c9736e9aae47d654849484c5ca532b5c5a40&tsid=4520138003"
  },
  {
    "id": "4520067",
    "title": "泵设备。为斯拉维扬斯克生态有限公司（ООО \"Славянск ЭКО\"）的ВТ-1项目供应泵设备（包括研发РКД、制造、现场交付）的询价",
    "originalTitle": "Насосное оборудование. Запрос предложений на поставку насосного оборудования (разработка РКД, изготовление, поставка на объект) для нужд ООО \"Славянск ЭКО\" под объект ВТ-1.",
    "category": "泵",
    "procurementType": "询价",
    "organizer": "ООО \"СЛАВЯНСК ЭКО\"",
    "publishTime": "2026-07-09T18:02:00+03:00",
    "deadline": "2026-07-20T12:00:00+03:00",
    "region": "353562 俄罗斯",
    "summary": "斯拉维扬斯克生态有限公司（ООО \"Славянск ЭКО\"）为ВТ-1项目公开询价，采购泵设备（含研发、制造及现场交付）。付款条件为交货后延期30-45天，其他方案可谈，预付款需提供银行保函。交货期要求最短。",
    "sourceUrl": "https://www.b2b-center.ru/market/nasosnoe-oborudovanie-zapros-predlozhenii-na-postavku-nasosnogo/tender-4520067/#btid=2&sqh=91d6c9736e9aae47d654849484c5ca532b5c5a40&tsid=4520067004"
  }
];

export const categories = Array.from(new Set(tenders.map((tender) => tender.category))).sort(
  (a, b) => a.localeCompare(b, "zh-CN")
);

export function getTenderById(id) {
  return tenders.find((tender) => tender.id === id);
}
