// Auto-generated by n8n. Do not edit manually.
export const tenders = [
  {
    "id": "4485683",
    "title": "443 - 用于场地雨棚的材料（钢筋、槽钢、瓦楞板、管材）",
    "originalTitle": "443 - ТМЦ для навеса над площадкой (арматура, швеллер, профнастил, труба)",
    "category": "金属结构",
    "procurementType": "询价采购（Запросы предложений）",
    "organizer": "ООО \"УК \"Колмар\"",
    "publishTime": "2026-06-11T05:45:00+03:00",
    "deadline": "2026-06-17T03:00:00+03:00",
    "region": "682860 俄罗斯",
    "summary": "采购用于场地雨棚的金属材料，包括钢筋、槽钢、瓦楞板和管材，共5件。交货至哈巴罗夫斯克边疆区阿亚角。电子采购平台进行。",
    "sourceUrl": "https://www.b2b-center.ru/market/443-tmts-dlia-navesa-nad-ploshchadkoi-armatura-shveller-profnastil/tender-4485683/#btid=2&sqh=25a74ba42ba5bb4e8b1acbb16dff486dbbcc841b&tsid=4485683004"
  },
  {
    "id": "4484330",
    "title": "采购轴承 - 询价单及短名单形成，用于乌多坎铜业有限责任公司",
    "originalTitle": "Закупка подшипников -Прайс лист и формирование Шорт-листа для нужд ООО \"Удоканская медь\"",
    "category": "轴承",
    "procurementType": "询价",
    "organizer": "ООО \"Удоканская медь\"",
    "publishTime": "2026-06-11T05:45:00+03:00",
    "deadline": "2026-06-19T11:00:00+03:00",
    "region": "俄罗斯 外贝加尔边疆区",
    "summary": "乌多坎铜业有限责任公司通过B2B-Center电子平台进行轴承采购询价，旨在收集报价并形成短名单。投标截止时间为2026年6月19日11:00，付款条件为货到后60天付款，交货地点为外贝加尔边疆区新查拉站（铁路运输）。",
    "sourceUrl": "https://www.b2b-center.ru/market/zakupka-podshipnikov-prais-list-i-formirovanie-short-lista-dlia-nuzhd/tender-4484330/#btid=2&sqh=25a74ba42ba5bb4e8b1acbb16dff486dbbcc841b&tsid=4484330004"
  }
];

export const categories = Array.from(new Set(tenders.map((tender) => tender.category))).sort(
  (a, b) => a.localeCompare(b, "zh-CN")
);

export function getTenderById(id) {
  return tenders.find((tender) => tender.id === id);
}
